name: calculadora_motorista
description: Calculadora de ganhos diários para motoristas de aplicativo.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0D0D0E"
  adaptive_icon_foreground: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
