services:
  - type: web
    name: calculadora-motorista-api
    branch: master
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: TOKEN_EXPIRE_DAYS
        value: "30"
      - key: CORS_ORIGINS
        value: "*"

  - type: web
    name: calculadora-motorista
    branch: master
    runtime: static
    staticPublishPath: ./build/web
    plan: free
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
