app = "calculadora-motorista"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  TOKEN_EXPIRE_DAYS = "30"
  CORS_ORIGINS = "*"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "motoristas_data"
  destination = "/data"
